package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

// buildCmd represents the build command
var buildCmd = &cobra.Command{
	Use:   "build",
	Short: "Generate AI context files (Exporter)",
	Long: `Combine specified documentation files into a single context file (e.g., .cursorrules) 
for AI agents as defined in cxb.yml.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		cfg, err := loadConfig("cxb.yml")
		if err != nil {
			return err
		}

		if len(cfg.Export) == 0 {
			cmd.Println("No export rules found in cxb.yml.")
			return nil
		}

		for _, export := range cfg.Export {
			var combined strings.Builder
			combined.WriteString("--- Context generated by cxb ---\n\n")

			for _, pattern := range export.Include {
				matches, err := filepath.Glob(pattern)
				if err != nil {
					return fmt.Errorf("failed to process pattern %s: %w", pattern, err)
				}

				for _, match := range matches {
					info, err := os.Stat(match)
					if err != nil || info.IsDir() {
						continue
					}

					content, err := os.ReadFile(match)
					if err != nil {
						return fmt.Errorf("failed to read file %s: %w", match, err)
					}

					combined.WriteString(fmt.Sprintf("--- File: %s ---\n", match))
					combined.Write(content)
					combined.WriteString("\n\n")
				}
			}

			err = os.WriteFile(export.Output, []byte(combined.String()), 0644)
			if err != nil {
				return fmt.Errorf("failed to write output file %s: %w", export.Output, err)
			}
			cmd.Printf("✅ Exported context to: %s\n", export.Output)
		}

		return nil
	},
}

func init() {
	rootCmd.AddCommand(buildCmd)
}
